"""Initial migration

Revision ID: 6650e908eebb
Revises: d039f7aa19e3
Create Date: 2024-08-30 18:15:04.482048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6650e908eebb'
down_revision: Union[str, None] = 'd039f7aa19e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cities_id', table_name='cities')
    op.drop_table('cities')
    op.drop_index('ix_temperatures_id', table_name='temperatures')
    op.drop_table('temperatures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temperatures_id', 'temperatures', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=65), nullable=False),
    sa.Column('additional_info', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_cities_id', 'cities', ['id'], unique=False)
    # ### end Alembic commands ###
