"""Initial migration

Revision ID: 66cff64ce1e6
Revises: d4dd3bba223d
Create Date: 2024-08-30 18:24:10.085318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cff64ce1e6'
down_revision: Union[str, None] = 'd4dd3bba223d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
